-- DROP USER KARTODROMO;

CREATE USER KARTODROMO
-- IDENTIFIED BY <password>
;

CREATE TABLE "AFFITTA" 
   ( "CELLULARE" VARCHAR2(13) NOT NULL ENABLE, 
	"NUMERO_TELAIO" VARCHAR2(17) NOT NULL ENABLE, 
	"NUMERO_KART" VARCHAR2(10) NOT NULL ENABLE, 
	 CONSTRAINT "PK_AFFITTA" PRIMARY KEY ("CELLULARE",
"NUMERO_TELAIO",
"NUMERO_KART")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "AFFITTA" ADD CONSTRAINT "FK_AFFITTA_UTENTE" FOREIGN KEY ("CELLULARE")
	  REFERENCES "UTENTE" ("CELLULARE") ENABLE;

ALTER TABLE "AFFITTA" ADD CONSTRAINT "FK_AFFITTA_KART" FOREIGN KEY ("NUMERO_KART",
"NUMERO_TELAIO")
	  REFERENCES "KART" ("NUMERO_KART",
"NUMERO_TELAIO") ENABLE;

GRANT
INSERT
    ON
    "AFFITTA" TO "USR_AMMINISTRATORE";

GRANT
SELECT
    ON
    "AFFITTA" TO "USR_AMMINISTRATORE";

GRANT
UPDATE
    ON
    "AFFITTA" TO "USR_AMMINISTRATORE";

;

CREATE TABLE "AMMINISTRATORE" 
   ( "CODICE_FISCALE" VARCHAR2(16), 
	 PRIMARY KEY ("CODICE_FISCALE")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "AMMINISTRATORE" ADD CONSTRAINT "FK_ADMIN_GESTORE" FOREIGN KEY ("CODICE_FISCALE")
	  REFERENCES "GESTORE" ("CODICE_FISCALE") ENABLE;

;

CREATE TABLE "DITTA" 
   ( "PARTITA_IVA" VARCHAR2(11), 
	"NOME" VARCHAR2(50) NOT NULL ENABLE, 
	"CELLULARE" VARCHAR2(13) NOT NULL ENABLE, 
	"VIA" VARCHAR2(50) NOT NULL ENABLE, 
	"CITTA" VARCHAR2(50) NOT NULL ENABLE, 
	"CIVICO" VARCHAR2(50) NOT NULL ENABLE, 
	 PRIMARY KEY ("PARTITA_IVA")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

GRANT
SELECT
    ON
    "DITTA" TO "USR_MANUTENTORE";

;

CREATE TABLE "EQUIPAGGIAMENTO" 
   ( "CODICE_A_BARRE" VARCHAR2(13), 
	"TIPO" VARCHAR2(20) NOT NULL ENABLE, 
	"NOME" VARCHAR2(20) NOT NULL ENABLE, 
	"TAGLIA" VARCHAR2(3) NOT NULL ENABLE, 
	 PRIMARY KEY ("CODICE_A_BARRE")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

GRANT
INSERT
    ON
    "EQUIPAGGIAMENTO" TO "USR_AMMINISTRATORE";

GRANT
SELECT
    ON
    "EQUIPAGGIAMENTO" TO "USR_AMMINISTRATORE";

GRANT
UPDATE
    ON
    "EQUIPAGGIAMENTO" TO "USR_AMMINISTRATORE";

;

CREATE TABLE "FATTURA" 
   ( "CODICE_FATTURA" VARCHAR2(20), 
	"NOME_DITTA" VARCHAR2(50) NOT NULL ENABLE, 
	"NOME" VARCHAR2(50) NOT NULL ENABLE, 
	"COGNOME" VARCHAR2(50) NOT NULL ENABLE, 
	 CONSTRAINT "CHK_FATTURA_MAIUSCOLO" CHECK (CODICE_FATTURA = UPPER(CODICE_FATTURA)) ENABLE, 
	 PRIMARY KEY ("CODICE_FATTURA")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

GRANT
INSERT
    ON
    "FATTURA" TO "USR_MANUTENTORE";

GRANT
SELECT
    ON
    "FATTURA" TO "USR_MANUTENTORE";

GRANT
UPDATE
    ON
    "FATTURA" TO "USR_MANUTENTORE";

;

CREATE TABLE "GARA" 
   ( "DATA_GARA" DATE, 
	"ORA_GARA" VARCHAR2(5), 
	"NOME_CAMPIONATO" VARCHAR2(40), 
	"NOME_PISTA" VARCHAR2(30) NOT NULL ENABLE, 
	 CONSTRAINT "CK_ORA_FORMATO_CORRETTO" CHECK (ORA_GARA >= '00:00'
    AND ORA_GARA <=
'23:59') ENABLE, 
	 CONSTRAINT "PK_GARA" PRIMARY KEY ("NOME_PISTA",
"DATA_GARA",
"ORA_GARA")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "GARA" ADD CONSTRAINT "FK_GARA_NOME_PISTA" FOREIGN KEY ("NOME_PISTA")
	  REFERENCES "PISTA" ("NOME_PISTA") ENABLE;

GRANT
DELETE
    ON
    "GARA" TO "USR_AMMINISTRATORE";

GRANT
INSERT
    ON
    "GARA" TO "USR_AMMINISTRATORE";

GRANT
SELECT
    ON
    "GARA" TO "USR_AMMINISTRATORE";

GRANT
UPDATE
    ON
    "GARA" TO "USR_AMMINISTRATORE";

;

CREATE TABLE "GESTORE" 
   ( "CODICE_FISCALE" VARCHAR2(16), 
	"NOME" VARCHAR2(20) NOT NULL ENABLE, 
	"COGNOME" VARCHAR2(20) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(30) NOT NULL ENABLE, 
	"CELLULARE" VARCHAR2(13) NOT NULL ENABLE, 
	 PRIMARY KEY ("CODICE_FISCALE")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

GRANT
SELECT
    ON
    "GESTORE" TO "USR_MANUTENTORE";

;

CREATE TABLE "INGAGGIA" 
   ( "LICENZA" VARCHAR2(40), 
	"NOME_TEAM" VARCHAR2(30), 
	"ANNO" NUMBER(4, 0), 
	 CONSTRAINT "CK_INGAGGIA_ANNO" CHECK (ANNO >= 2000
    AND ANNO <= 2100) ENABLE, 
	 CONSTRAINT "PK_INGAGGIA" PRIMARY KEY ("LICENZA",
"NOME_TEAM",
"ANNO")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "INGAGGIA" ADD CONSTRAINT "FK_INGAGGIA_TEAM" FOREIGN KEY ("NOME_TEAM")
	  REFERENCES "TEAM" ("NOME_TEAM") ENABLE;

ALTER TABLE "INGAGGIA" ADD CONSTRAINT "FK_INGAGGIA_PILOTA" FOREIGN KEY ("LICENZA")
	  REFERENCES "PILOTA" ("LICENZA") ENABLE;

CREATE OR REPLACE
EDITIONABLE TRIGGER "T_ETA_MINIMA_INGAGGIO_TEAM" 
BEFORE
INSERT
    OR
UPDATE
    ON
    INGAGGIA FOR EACH ROW
DECLARE
        v_data_nascita DATE;

v_eta_nell_anno NUMBER;
BEGIN
    SELECT
    DATA_NASCITA
INTO
    v_data_nascita
FROM
    PILOTA
WHERE
    LICENZA = :NEW.LICENZA;

v_eta_nell_anno := :NEW.ANNO - EXTRACT(YEAR FROM v_data_nascita);

IF v_eta_nell_anno <= 14 THEN
        RAISE_APPLICATION_ERROR(-20080, 'Errore: Il pilota deve avere più di 14 anni.');
END IF;

EXCEPTION
WHEN NO_DATA_FOUND THEN RAISE_APPLICATION_ERROR(-20001, 'Pilota non trovato.');
END;

/
ALTER TRIGGER "T_ETA_MINIMA_INGAGGIO_TEAM" ENABLE;

CREATE OR REPLACE
EDITIONABLE TRIGGER "T_LIMITE_PILOTI_TEAM" 
BEFORE
INSERT
    ON
    INGAGGIA FOR EACH ROW
DECLARE
        v_conteggio NUMBER;
BEGIN
    SELECT
    COUNT(*)
INTO
    v_conteggio
FROM
    INGAGGIA
WHERE
    NOME_TEAM = :NEW.NOME_TEAM
    AND ANNO = :NEW.ANNO;

IF v_conteggio >= 2 THEN
        RAISE_APPLICATION_ERROR(-20046, 'Un team non può ingaggiare più di 2 piloti l''anno.');
END IF;
END;

/
ALTER TRIGGER "T_LIMITE_PILOTI_TEAM" ENABLE;

GRANT
DELETE
    ON
    "INGAGGIA" TO "USR_AMMINISTRATORE";

GRANT
INSERT
    ON
    "INGAGGIA" TO "USR_AMMINISTRATORE";

GRANT
SELECT
    ON
    "INGAGGIA" TO "USR_AMMINISTRATORE";

GRANT
UPDATE
    ON
    "INGAGGIA" TO "USR_AMMINISTRATORE";

;

CREATE TABLE "INTERVENTO_RIPARAZIONE" 
   ( "CODICE_INTERVENTO" NUMBER(4, 0), 
	"DATA_INIZIO" DATE NOT NULL ENABLE, 
	"DATA_FINE" DATE, 
	"ORA_INIZIO" VARCHAR2(5) NOT NULL ENABLE, 
	"ORA_FINE" VARCHAR2(5), 
	"TIPO_GUASTO" VARCHAR2(500), 
	"TIPI_RICAMBI" VARCHAR2(500), 
	"COSTO" NUMBER(8, 2), 
	"CODICE_FATTURA" VARCHAR2(20) NOT NULL ENABLE, 
	"NUMERO_KART" VARCHAR2(10) NOT NULL ENABLE, 
	"NUMERO_TELAIO" VARCHAR2(17) NOT NULL ENABLE, 
	"PARTITA_IVA" VARCHAR2(11) NOT NULL ENABLE, 
	"CODICE_FISCALE" VARCHAR2(16), 
	 CONSTRAINT "CK_INTERVENTO_ORA_INIZIO" CHECK (ORA_INIZIO >= '00:00'
    AND ORA_INIZIO <=
'23:59') ENABLE, 
	 CONSTRAINT "CK_INTERVENTO_ORA_FINE" CHECK (ORA_FINE >= '00:00'
    AND ORA_FINE <= '23:59') ENABLE, 
	 PRIMARY KEY ("CODICE_INTERVENTO")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "INTERVENTO_RIPARAZIONE" ADD CONSTRAINT "FK_INTERVENTO_FATTURA" FOREIGN KEY ("CODICE_FATTURA")
	  REFERENCES "FATTURA" ("CODICE_FATTURA") ENABLE;

ALTER TABLE "INTERVENTO_RIPARAZIONE" ADD CONSTRAINT "FK_INTERVENTO_PARTITA_IVA" FOREIGN KEY ("PARTITA_IVA")
	  REFERENCES "DITTA" ("PARTITA_IVA") ENABLE;

ALTER TABLE "INTERVENTO_RIPARAZIONE" ADD CONSTRAINT "FK_INTERVENTO_KART" FOREIGN KEY ("NUMERO_KART",
"NUMERO_TELAIO")
	  REFERENCES "KART" ("NUMERO_KART",
"NUMERO_TELAIO") ENABLE;

ALTER TABLE "INTERVENTO_RIPARAZIONE" ADD CONSTRAINT "FK_INTERVENTO_MANUTENTORE" FOREIGN KEY ("CODICE_FISCALE")
	  REFERENCES "MANUTENTORE" ("CODICE_FISCALE") ENABLE;

CREATE OR REPLACE
EDITIONABLE TRIGGER "T_COERENZA_DATE_RIPARAZIONE" 
BEFORE
INSERT
    OR
UPDATE
    ON
    INTERVENTO_RIPARAZIONE FOR EACH ROW
BEGIN
        IF :NEW.DATA_FINE IS NOT NULL THEN
        IF :NEW.DATA_FINE < :NEW.DATA_INIZIO THEN
            RAISE_APPLICATION_ERROR(-20051, 'Data fine antecedente a inizio.');

ELSIF :NEW.DATA_FINE = :NEW.DATA_INIZIO
AND :NEW.ORA_FINE <= :NEW.ORA_INIZIO THEN
            RAISE_APPLICATION_ERROR(-20052, 'Ora fine non valida.');
END IF;
END IF;
END;

/
ALTER TRIGGER "T_COERENZA_DATE_RIPARAZIONE" ENABLE;

CREATE OR REPLACE
EDITIONABLE TRIGGER "T_CHECK_KART_LIBERO" 
BEFORE
INSERT
    ON
    INTERVENTO_RIPARAZIONE FOR EACH ROW
DECLARE
        v_count NUMBER;
BEGIN
    SELECT
    COUNT(*)
INTO
    v_count
FROM
    INTERVENTO_RIPARAZIONE
WHERE
    NUMERO_KART = :NEW.NUMERO_KART
    AND NUMERO_TELAIO = :NEW.NUMERO_TELAIO
    AND DATA_FINE IS NULL;

IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20060, 'Errore: Kart già in riparazione.');
END IF;
END;

/
ALTER TRIGGER "T_CHECK_KART_LIBERO" ENABLE;

GRANT
INSERT
    ON
    "INTERVENTO_RIPARAZIONE" TO "USR_MANUTENTORE";

GRANT
SELECT
    ON
    "INTERVENTO_RIPARAZIONE" TO "USR_MANUTENTORE";

GRANT
UPDATE
    ON
    "INTERVENTO_RIPARAZIONE" TO "USR_MANUTENTORE";

;

CREATE TABLE "KART" 
   ( "NUMERO_TELAIO" VARCHAR2(17), 
	"NUMERO_KART" VARCHAR2(10), 
	"MODELLO" VARCHAR2(50) NOT NULL ENABLE, 
	"CILINDRATA" NUMBER(4, 0) NOT NULL ENABLE, 
	 CONSTRAINT "PK_KART" PRIMARY KEY ("NUMERO_KART",
"NUMERO_TELAIO")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

GRANT
SELECT
    ON
    "KART" TO "USR_MANUTENTORE";

GRANT
UPDATE
    ON
    "KART" TO "USR_MANUTENTORE";

;

CREATE TABLE "MANUTENTORE" 
   ( "CODICE_FISCALE" VARCHAR2(16), 
	 PRIMARY KEY ("CODICE_FISCALE")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "MANUTENTORE" ADD CONSTRAINT "FK_ADMIN_GESTORE2" FOREIGN KEY ("CODICE_FISCALE")
	  REFERENCES "GESTORE" ("CODICE_FISCALE") ENABLE;

;

CREATE TABLE "PACCHETTO_GARA" 
   ( "NOME_PACCHETTO" VARCHAR2(30), 
	"DURATA" NUMBER(3, 0) NOT NULL ENABLE, 
	"PREZZO" NUMBER(8, 2) NOT NULL ENABLE, 
	"NUMERO_PARTECIPANTI" NUMBER(4, 0) NOT NULL ENABLE, 
	"NOME_PISTA" VARCHAR2(30) NOT NULL ENABLE, 
	 PRIMARY KEY ("NOME_PACCHETTO")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "PACCHETTO_GARA" ADD CONSTRAINT "FK_PACCHETTO_GARA_NOME_PISTA" FOREIGN KEY ("NOME_PISTA")
	  REFERENCES "PISTA" ("NOME_PISTA") ENABLE;

GRANT
INSERT
    ON
    "PACCHETTO_GARA" TO "USR_AMMINISTRATORE";

GRANT
SELECT
    ON
    "PACCHETTO_GARA" TO "USR_AMMINISTRATORE";

GRANT
UPDATE
    ON
    "PACCHETTO_GARA" TO "USR_AMMINISTRATORE";

;

CREATE TABLE "PAGAMENTO" 
   ( "DATA_PAGAMENTO" DATE, 
	"ORA_PAGAMENTO" VARCHAR2(5), 
	"MODALITA" VARCHAR2(30), 
	"DATA_PRENOTAZIONE" DATE, 
	"ORA_PRENOTAZIONE" VARCHAR2(5), 
	"NOME_TEAM" VARCHAR2(30), 
	 CONSTRAINT "CK_PAGAMENTO_ORA_FORMATO" CHECK (ORA_PAGAMENTO >= '00:00'
    AND
ORA_PAGAMENTO <= '23:59') ENABLE, 
	 CONSTRAINT "CK_PAGAMENTO_MODALITA" CHECK (MODALITA IN ('Contanti', 'Carta Credito',
'Bancomat', 'Bonifico')) ENABLE, 
	 CONSTRAINT "PK_PAGAMENTO" PRIMARY KEY ("DATA_PAGAMENTO",
"ORA_PAGAMENTO")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "PAGAMENTO" ADD CONSTRAINT "FK_TEAM" FOREIGN KEY ("NOME_TEAM")
	  REFERENCES "TEAM" ("NOME_TEAM") ENABLE;

ALTER TABLE "PAGAMENTO" ADD CONSTRAINT "FK_PRENOTAZIONE" FOREIGN KEY ("DATA_PRENOTAZIONE",
"ORA_PRENOTAZIONE")
	  REFERENCES "PRENOTAZIONE" ("DATA_PRENOTAZIONE",
"ORA_PRENOTAZIONE") ENABLE;

CREATE OR REPLACE
EDITIONABLE TRIGGER "T_COERENZA_DATE_PAGAMENTO" 
BEFORE
INSERT
    OR
UPDATE
    ON
    PAGAMENTO FOR EACH ROW
BEGIN
        IF :NEW.DATA_PAGAMENTO < :NEW.DATA_PRENOTAZIONE THEN
        RAISE_APPLICATION_ERROR(-20041, 'Pagamento precedente alla prenotazione.');
END IF;
END;

/
ALTER TRIGGER "T_COERENZA_DATE_PAGAMENTO" ENABLE;

CREATE OR REPLACE
EDITIONABLE TRIGGER "T_PAGAMENTO_CONSOLIDATO_IMMUTABILE" 
BEFORE
UPDATE
    ON
    PAGAMENTO FOR EACH ROW
BEGIN
        RAISE_APPLICATION_ERROR(-20042, 'Vietato modificare un pagamento consolidato.');
END;

/
ALTER TRIGGER "T_PAGAMENTO_CONSOLIDATO_IMMUTABILE" ENABLE;

GRANT
DELETE
    ON
    "PAGAMENTO" TO "USR_AMMINISTRATORE";

GRANT
INSERT
    ON
    "PAGAMENTO" TO "USR_AMMINISTRATORE";

GRANT
SELECT
    ON
    "PAGAMENTO" TO "USR_AMMINISTRATORE";

GRANT
UPDATE
    ON
    "PAGAMENTO" TO "USR_AMMINISTRATORE";

;

CREATE TABLE "PILOTA" 
   ( "LICENZA" VARCHAR2(40), 
	"NOME" VARCHAR2(20) NOT NULL ENABLE, 
	"COGNOME" VARCHAR2(20) NOT NULL ENABLE, 
	"PESO" NUMBER(3, 0) NOT NULL ENABLE, 
	"CATEGORIA" VARCHAR2(20) NOT NULL ENABLE, 
	"DATA_NASCITA" DATE NOT NULL ENABLE, 
	 PRIMARY KEY ("LICENZA")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE OR REPLACE
EDITIONABLE TRIGGER "T_CONTROLLO_PESO_PILOTA" 
BEFORE
INSERT
    OR
UPDATE
    ON
    PILOTA FOR EACH ROW
BEGIN
        IF :NEW.PESO < 30
        OR :NEW.PESO > 150 THEN
        RAISE_APPLICATION_ERROR(-20070, 'Peso pilota non valido.');
END IF;
END;

/
ALTER TRIGGER "T_CONTROLLO_PESO_PILOTA" ENABLE;

GRANT
DELETE
    ON
    "PILOTA" TO "USR_AMMINISTRATORE";

GRANT
INSERT
    ON
    "PILOTA" TO "USR_AMMINISTRATORE";

GRANT
SELECT
    ON
    "PILOTA" TO "USR_AMMINISTRATORE";

GRANT
UPDATE
    ON
    "PILOTA" TO "USR_AMMINISTRATORE";

;

CREATE TABLE "PISTA" 
   ( "NOME_PISTA" VARCHAR2(30), 
	"LUNGHEZZA_METRI" NUMBER(4, 0) NOT NULL ENABLE, 
	 PRIMARY KEY ("NOME_PISTA")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

GRANT
INSERT
    ON
    "PISTA" TO "USR_AMMINISTRATORE";

GRANT
SELECT
    ON
    "PISTA" TO "USR_AMMINISTRATORE";

GRANT
UPDATE
    ON
    "PISTA" TO "USR_AMMINISTRATORE";

;

CREATE TABLE "PRENOTAZIONE" 
   ( "DATA_PRENOTAZIONE" DATE, 
	"ORA_PRENOTAZIONE" VARCHAR2(5), 
	"QUOTA_ISCRIZIONE" NUMBER(3, 0), 
	"NUMERO_PARTECIPANTI_EFFETTIVO" NUMBER(3, 0), 
	"NOME_PISTA" VARCHAR2(30) NOT NULL ENABLE, 
	"DATA_GARA" DATE NOT NULL ENABLE, 
	"ORA_GARA" VARCHAR2(5) NOT NULL ENABLE, 
	"CELLULARE" VARCHAR2(13) NOT NULL ENABLE, 
	"NOME_PACCHETTO" VARCHAR2(30) NOT NULL ENABLE, 
	"CODICE_FISCALE" VARCHAR2(16) NOT NULL ENABLE, 
	 CONSTRAINT "CK_PRENOT_ORA_FORMATO" CHECK (ORA_PRENOTAZIONE >= '00:00'
    AND
ORA_PRENOTAZIONE <= '23:59') ENABLE, 
	 CONSTRAINT "CK_PRENOT_QUOTA_POSITIVA" CHECK (QUOTA_ISCRIZIONE >= 0) ENABLE, 
	 CONSTRAINT "CK_PRENOT_PART_POSITIVI" CHECK (NUMERO_PARTECIPANTI_EFFETTIVO > 0) ENABLE, 
	 CONSTRAINT "PK_PRENOTAZIONE" PRIMARY KEY ("DATA_PRENOTAZIONE",
"ORA_PRENOTAZIONE")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "PRENOTAZIONE" ADD CONSTRAINT "FK_PRENOTAZIONE_GARA" FOREIGN KEY ("NOME_PISTA",
"DATA_GARA",
"ORA_GARA")
	  REFERENCES "GARA" ("NOME_PISTA",
"DATA_GARA",
"ORA_GARA") ENABLE;

ALTER TABLE "PRENOTAZIONE" ADD CONSTRAINT "FK_PRENOTAZIONE_UTENTE" FOREIGN KEY ("CELLULARE")
	  REFERENCES "UTENTE" ("CELLULARE") ENABLE;

ALTER TABLE "PRENOTAZIONE" ADD CONSTRAINT "FK_PRENOTAZIONE_PACCHETTO" FOREIGN KEY ("NOME_PACCHETTO")
	  REFERENCES "PACCHETTO_GARA" ("NOME_PACCHETTO") ENABLE;

ALTER TABLE "PRENOTAZIONE" ADD CONSTRAINT "FK_PRENOTAZIONE_AMMINISTRATORE" FOREIGN KEY ("CODICE_FISCALE")
	  REFERENCES "AMMINISTRATORE" ("CODICE_FISCALE") ENABLE;

CREATE OR REPLACE
EDITIONABLE TRIGGER "MINIMO_PARTECIPANTI" 
BEFORE
INSERT
    OR
UPDATE
    ON
    PRENOTAZIONE FOR EACH ROW
DECLARE
        MINIMO_RICHIESTO NUMBER;
BEGIN
    SELECT
    NUMERO_PARTECIPANTI
INTO
    MINIMO_RICHIESTO
FROM
    PACCHETTO_GARA
WHERE
    NOME_PACCHETTO = :NEW.NOME_PACCHETTO;

IF :NEW.NUMERO_PARTECIPANTI_EFFETTIVO < MINIMO_RICHIESTO THEN
        RAISE_APPLICATION_ERROR(-20002, 'Partecipanti sotto il minimo.');
END IF;

EXCEPTION
WHEN NO_DATA_FOUND THEN RAISE_APPLICATION_ERROR(-20004, 'Pacchetto gara non trovato.');
END;

/
ALTER TRIGGER "MINIMO_PARTECIPANTI" ENABLE;

CREATE OR REPLACE
EDITIONABLE TRIGGER "T_PRENOTAZIONE_FUTURA" 
BEFORE
INSERT
    ON
    PRENOTAZIONE FOR EACH ROW
BEGIN
        IF :NEW.DATA_GARA < TRUNC(SYSDATE) THEN
        RAISE_APPLICATION_ERROR(-20053, 'Operazione negata: gara passata.');
END IF;
END;

/
ALTER TRIGGER "T_PRENOTAZIONE_FUTURA" ENABLE;

GRANT
DELETE
    ON
    "PRENOTAZIONE" TO "USR_AMMINISTRATORE";

GRANT
INSERT
    ON
    "PRENOTAZIONE" TO "USR_AMMINISTRATORE";

GRANT
SELECT
    ON
    "PRENOTAZIONE" TO "USR_AMMINISTRATORE";

GRANT
UPDATE
    ON
    "PRENOTAZIONE" TO "USR_AMMINISTRATORE";

;

CREATE TABLE "RICHIEDE" 
   ( "CELLULARE" VARCHAR2(13), 
	"CODICE_A_BARRE" VARCHAR2(13), 
	"DATA_RICHIESTA" DATE, 
	"ORA_RICHIESTA" VARCHAR2(5), 
	 CONSTRAINT "CK_RICHIEDE_ORA_FORMATO" CHECK (ORA_RICHIESTA >= '00:00'
    AND ORA_RICHIESTA
<= '23:59') ENABLE, 
	 CONSTRAINT "PK_RICHIEDE" PRIMARY KEY ("CELLULARE",
"CODICE_A_BARRE",
"DATA_RICHIESTA",
"ORA_RICHIESTA")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "RICHIEDE" ADD CONSTRAINT "FK_RICHIEDE_UTENTE" FOREIGN KEY ("CELLULARE")
	  REFERENCES "UTENTE" ("CELLULARE") ENABLE;

ALTER TABLE "RICHIEDE" ADD CONSTRAINT "FK_RICHIEDE_EQUIPAGGIAMENTO" FOREIGN KEY ("CODICE_A_BARRE")
	  REFERENCES "EQUIPAGGIAMENTO" ("CODICE_A_BARRE") ENABLE;

GRANT
DELETE
    ON
    "RICHIEDE" TO "USR_AMMINISTRATORE";

GRANT
INSERT
    ON
    "RICHIEDE" TO "USR_AMMINISTRATORE";

GRANT
SELECT
    ON
    "RICHIEDE" TO "USR_AMMINISTRATORE";

GRANT
UPDATE
    ON
    "RICHIEDE" TO "USR_AMMINISTRATORE";

;

CREATE TABLE "TEAM" 
   ( "NOME_TEAM" VARCHAR2(30), 
	"SEDE" VARCHAR2(30) NOT NULL ENABLE, 
	"EMAIL_AZIENDALE" VARCHAR2(50) NOT NULL ENABLE, 
	 CONSTRAINT "CK_TEAM_EMAIL_FORMATO" CHECK (EMAIL_AZIENDALE LIKE '%@%.%') ENABLE, 
	 PRIMARY KEY ("NOME_TEAM")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

GRANT
DELETE
    ON
    "TEAM" TO "USR_AMMINISTRATORE";

GRANT
INSERT
    ON
    "TEAM" TO "USR_AMMINISTRATORE";

GRANT
SELECT
    ON
    "TEAM" TO "USR_AMMINISTRATORE";

GRANT
UPDATE
    ON
    "TEAM" TO "USR_AMMINISTRATORE";

;

CREATE TABLE "TELEMETRIA" 
   ( "NUMERO_GIRO" NUMBER(3, 0), 
	"TEMPO_GIRO" INTERVAL DAY (0) TO SECOND (3) NOT NULL ENABLE, 
	"POSIZIONE" NUMBER(2, 0) NOT NULL ENABLE, 
	"DATA_GARA" DATE, 
	"ORA_GARA" VARCHAR2(5), 
	"NUMERO_TELAIO" VARCHAR2(17), 
	"NUMERO_KART" VARCHAR2(10), 
	"LICENZA" VARCHAR2(40), 
	"NOME_PISTA" VARCHAR2(30), 
	 CONSTRAINT "CK_TELEMETRIA_GIRO_VALIDO" CHECK (NUMERO_GIRO > 0) ENABLE, 
	 CONSTRAINT "CK_TELEMETRIA_POS_VALIDA" CHECK (POSIZIONE > 0) ENABLE, 
	 CONSTRAINT "CK_TELEMETRIA_TIPO_PILOTA" CHECK (
("LICENZA" IS NOT NULL
    AND "NUMERO_TELAIO" IS NULL
    AND "NUMERO_KART" IS NULL)
OR
("LICENZA" IS NULL
    AND "NUMERO_TELAIO" IS NOT NULL
    AND "NUMERO_KART" IS NOT NULL)
) ENABLE, 
	 CONSTRAINT "PK_TELEMETRIA" PRIMARY KEY ("NOME_PISTA",
"DATA_GARA",
"ORA_GARA",
"NUMERO_GIRO",
"POSIZIONE")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "TELEMETRIA" ADD CONSTRAINT "FK_TELEMETRIA_GARA" FOREIGN KEY ("NOME_PISTA",
"DATA_GARA",
"ORA_GARA")
	  REFERENCES "GARA" ("NOME_PISTA",
"DATA_GARA",
"ORA_GARA") ENABLE;

ALTER TABLE "TELEMETRIA" ADD CONSTRAINT "FK_TELEMETRIA_PILOTA" FOREIGN KEY ("LICENZA")
	  REFERENCES "PILOTA" ("LICENZA") ENABLE;

ALTER TABLE "TELEMETRIA" ADD CONSTRAINT "FK_TELEMETRIA_KART" FOREIGN KEY ("NUMERO_KART",
"NUMERO_TELAIO")
	  REFERENCES "KART" ("NUMERO_KART",
"NUMERO_TELAIO") ENABLE;

;

CREATE TABLE "UTENTE" 
   ( "CELLULARE" VARCHAR2(13), 
	"NOME" VARCHAR2(20) NOT NULL ENABLE, 
	"COGNOME" VARCHAR2(20) NOT NULL ENABLE, 
	 PRIMARY KEY ("CELLULARE")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

GRANT
DELETE
    ON
    "UTENTE" TO "USR_AMMINISTRATORE";

GRANT
INSERT
    ON
    "UTENTE" TO "USR_AMMINISTRATORE";

GRANT
SELECT
    ON
    "UTENTE" TO "USR_AMMINISTRATORE";

GRANT
UPDATE
    ON
    "UTENTE" TO "USR_AMMINISTRATORE";

;

CREATE OR REPLACE
FORCE EDITIONABLE VIEW "V_CLASSIFICA_FINALE_GARA" ("DATA_GARA",
"ORA_GARA",
"NOME_PISTA",
"POSIZIONE_FINALE",
"PILOTA",
"NUMERO_KART",
"GIRI_TOTALI") AS 
  SELECT 
    T.DATA_GARA, 
    T.ORA_GARA, 
    T.NOME_PISTA, 
    T.POSIZIONE AS POSIZIONE_FINALE, 
    COALESCE(P.COGNOME || ' ' || P.NOME, T.LICENZA) AS PILOTA,
    T.NUMERO_KART,
    T.NUMERO_GIRO AS GIRI_TOTALI
FROM
    TELEMETRIA T
LEFT JOIN PILOTA P ON
    T.LICENZA = P.LICENZA
WHERE
    T.NUMERO_GIRO = (
    SELECT
        MAX(T2.NUMERO_GIRO)
    FROM
        TELEMETRIA T2
    WHERE
        T2.DATA_GARA = T.DATA_GARA
        AND T2.ORA_GARA = T.ORA_GARA
        AND T2.NOME_PISTA = T.NOME_PISTA
);

GRANT
SELECT
    ON
    "V_CLASSIFICA_FINALE_GARA" TO "USR_AMMINISTRATORE";

;

CREATE OR REPLACE
FORCE EDITIONABLE VIEW "V_MANUTENZIONE_ATTIVA" ("CODICE_INTERVENTO",
"NUMERO_KART",
"NUMERO_TELAIO",
"TIPO_GUASTO",
"NOME_DITTA",
"CONTATTO_DITTA") AS 
  SELECT
    I.CODICE_INTERVENTO,
    I.NUMERO_KART,
    I.NUMERO_TELAIO,
    I.TIPO_GUASTO, 
       D.NOME AS NOME_DITTA,
    D.CELLULARE AS CONTATTO_DITTA
FROM
    INTERVENTO_RIPARAZIONE I
JOIN DITTA D ON
    I.PARTITA_IVA = D.PARTITA_IVA
WHERE
    I.DATA_FINE IS NULL;

GRANT
SELECT
    ON
    "V_MANUTENZIONE_ATTIVA" TO "USR_MANUTENTORE";

;

CREATE OR REPLACE
FORCE EDITIONABLE VIEW "V_PILOTI_TEAM_ATTIVI" ("NOME",
"COGNOME",
"CATEGORIA",
"NOME_TEAM",
"ANNO") AS 
  SELECT
    P.NOME,
    P.COGNOME,
    P.CATEGORIA,
    I.NOME_TEAM,
    I.ANNO
FROM
    PILOTA P
JOIN INGAGGIA I ON
    P.LICENZA = I.LICENZA
WHERE
    I.ANNO = EXTRACT(YEAR FROM SYSDATE);

GRANT
SELECT
    ON
    "V_PILOTI_TEAM_ATTIVI" TO "USR_AMMINISTRATORE";

;

CREATE OR REPLACE
FORCE EDITIONABLE VIEW "V_REPORT_GARA_COMPLETO" ("DATA_GARA",
"ORA_GARA",
"NOME_PISTA",
"NUMERO_GIRO",
"POSIZIONE",
"PILOTA",
"TEMPO_GIRO",
"NUMERO_KART") AS 
  SELECT 
    T.DATA_GARA, 
    T.ORA_GARA, 
    T.NOME_PISTA, 
    T.NUMERO_GIRO, 
    T.POSIZIONE, 
    COALESCE(P.COGNOME || ' ' || P.NOME, T.LICENZA) AS PILOTA,
    T.TEMPO_GIRO, 
    T.NUMERO_KART
FROM
    TELEMETRIA T
LEFT JOIN PILOTA P ON
    T.LICENZA = P.LICENZA;

GRANT
SELECT
    ON
    "V_REPORT_GARA_COMPLETO" TO "USR_AMMINISTRATORE";

;

CREATE OR REPLACE
FORCE EDITIONABLE VIEW "V_REPORT_PRENOTAZIONI" ("DATA_PRENOTAZIONE",
"ORA_PRENOTAZIONE",
"DATA_GARA",
"NOME",
"COGNOME",
"CELLULARE",
"NOME_PACCHETTO",
"NOME_PISTA") AS 
  SELECT
    P.DATA_PRENOTAZIONE,
    P.ORA_PRENOTAZIONE,
    P.DATA_GARA, 
       U.NOME,
    U.COGNOME,
    U.CELLULARE, 
       P.NOME_PACCHETTO,
    P.NOME_PISTA
FROM
    PRENOTAZIONE P
JOIN UTENTE U ON
    P.CELLULARE = U.CELLULARE;

GRANT
SELECT
    ON
    "V_REPORT_PRENOTAZIONI" TO "USR_AMMINISTRATORE";

;

CREATE OR REPLACE
PROCEDURE KARTODROMO.SP_AGGIORNA_DETTAGLI_RIPARAZIONE (
    p_cod_intervento NUMBER,
p_tipo_guasto VARCHAR2,
p_tipi_ricambi VARCHAR2
) IS
    v_num_kart VARCHAR2(100);

v_partita_iva VARCHAR2(100);

v_check NUMBER;

BEGIN
    BEGIN
        SELECT
    NUMERO_KART,
    PARTITA_IVA
INTO
    v_num_kart,
    v_partita_iva
FROM
    INTERVENTO_RIPARAZIONE
WHERE
    CODICE_INTERVENTO = p_cod_intervento
    AND DATA_FINE IS NULL;

EXCEPTION
WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20095, 'Errore: Intervento inesistente o gia chiuso.');
END;

SELECT
    COUNT(*)
INTO
    v_check
FROM
    KART
WHERE
    NUMERO_KART = v_num_kart;

IF v_check = 0 THEN
        RAISE_APPLICATION_ERROR(-20061, 'Errore: Integrita violata, il Kart associato non esiste piu.');
END IF;

SELECT
    COUNT(*)
INTO
    v_check
FROM
    DITTA
WHERE
    PARTITA_IVA = v_partita_iva;

IF v_check = 0 THEN
        RAISE_APPLICATION_ERROR(-20062, 'Errore: Integrita violata, la Ditta associata non esiste piu.');
END IF;

UPDATE
    INTERVENTO_RIPARAZIONE
SET
    TIPO_GUASTO = p_tipo_guasto,
    TIPI_RICAMBI = p_tipi_ricambi
WHERE
    CODICE_INTERVENTO = p_cod_intervento;
END;

CREATE OR REPLACE
PROCEDURE KARTODROMO.SP_APRI_RIPARAZIONE (
    p_cod_intervento NUMBER,
p_num_kart VARCHAR2,
p_num_telaio VARCHAR2,
    p_partita_iva VARCHAR2,
p_manutentore VARCHAR2,
p_tipo_guasto VARCHAR2
) IS
    v_check NUMBER;
BEGIN
    SELECT
    COUNT(*)
INTO
    v_check
FROM
    KART
WHERE
    NUMERO_KART = p_num_kart
    AND NUMERO_TELAIO = p_num_telaio;

IF v_check = 0 THEN
        RAISE_APPLICATION_ERROR(-20061, 'Errore: Il Kart specificato non esiste nel sistema.');
END IF;

SELECT
    COUNT(*)
INTO
    v_check
FROM
    DITTA
WHERE
    PARTITA_IVA = p_partita_iva;

IF v_check = 0 THEN
        RAISE_APPLICATION_ERROR(-20062, 'Errore: La Ditta specificata non esiste.');
END IF;

SELECT
    COUNT(*)
INTO
    v_check
FROM
    INTERVENTO_RIPARAZIONE
WHERE
    NUMERO_KART = p_num_kart
    AND NUMERO_TELAIO = p_num_telaio
    AND DATA_FINE IS NULL;

IF v_check > 0 THEN
        RAISE_APPLICATION_ERROR(-20060, 'Errore: Kart gia in riparazione.');
END IF;

INSERT
    INTO
    INTERVENTO_RIPARAZIONE (CODICE_INTERVENTO,
    NUMERO_KART,
    NUMERO_TELAIO,
    PARTITA_IVA,
    CODICE_FISCALE,
    TIPO_GUASTO,
    DATA_INIZIO,
    ORA_INIZIO)
VALUES (p_cod_intervento,
p_num_kart,
p_num_telaio,
p_partita_iva,
p_manutentore,
p_tipo_guasto,
TRUNC(SYSDATE),
TO_CHAR(SYSDATE, 'HH24:MI'));
END;

/
-- 2. Aggiorna i dettagli dell'intervento
CREATE OR REPLACE
PROCEDURE SP_AGGIORNA_DETTAGLI_RIPARAZIONE (
    p_cod_intervento NUMBER,
p_tipo_guasto VARCHAR2,
p_tipi_ricambi VARCHAR2
) IS
    v_num_kart VARCHAR2(100);

v_partita_iva VARCHAR2(100);

v_check NUMBER;
BEGIN
BEGIN
        SELECT
    NUMERO_KART,
    PARTITA_IVA
INTO
    v_num_kart,
    v_partita_iva
FROM
    INTERVENTO_RIPARAZIONE
WHERE
    CODICE_INTERVENTO = p_cod_intervento
    AND DATA_FINE IS NULL;

EXCEPTION
WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20095, 'Errore: Intervento inesistente o gia chiuso.');
END;

SELECT
    COUNT(*)
INTO
    v_check
FROM
    KART
WHERE
    NUMERO_KART = v_num_kart;

IF v_check = 0 THEN
        RAISE_APPLICATION_ERROR(-20061, 'Errore: Integrita violata, il Kart associato non esiste piu.');
END IF;

SELECT
    COUNT(*)
INTO
    v_check
FROM
    DITTA
WHERE
    PARTITA_IVA = v_partita_iva;

IF v_check = 0 THEN
        RAISE_APPLICATION_ERROR(-20062, 'Errore: Integrita violata, la Ditta associata non esiste piu.');
END IF;

UPDATE
    INTERVENTO_RIPARAZIONE
SET
    TIPO_GUASTO = p_tipo_guasto,
    TIPI_RICAMBI = p_tipi_ricambi
WHERE
    CODICE_INTERVENTO = p_cod_intervento;
END;

/
-- 3. Conclude l'intervento
CREATE OR REPLACE
PROCEDURE SP_CHIUDI_RIPARAZIONE (
    p_cod_intervento NUMBER,
p_cod_fattura VARCHAR2,
p_costo NUMBER
) IS
    v_num_kart VARCHAR2(100);

v_check NUMBER;
BEGIN
BEGIN
        SELECT
    NUMERO_KART
INTO
    v_num_kart
FROM
    INTERVENTO_RIPARAZIONE
WHERE
    CODICE_INTERVENTO = p_cod_intervento
    AND DATA_FINE IS NULL;

EXCEPTION
WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20096, 'Errore: Impossibile chiudere un intervento inesistente o gia chiuso.');
END;

SELECT
    COUNT(*)
INTO
    v_check
FROM
    FATTURA
WHERE
    CODICE_FATTURA = p_cod_fattura;

IF v_check = 0 THEN
        RAISE_APPLICATION_ERROR(-20063, 'Errore: La Fattura specificata non esiste nel sistema.');
END IF;

SELECT
    COUNT(*)
INTO
    v_check
FROM
    KART
WHERE
    NUMERO_KART = v_num_kart;

IF v_check = 0 THEN
        RAISE_APPLICATION_ERROR(-20061, 'Errore: Integrita violata, il Kart non esiste piu.');
END IF;

UPDATE
    INTERVENTO_RIPARAZIONE
SET
    DATA_FINE = TRUNC(SYSDATE),
    ORA_FINE = TO_CHAR(SYSDATE, 'HH24:MI'),
    CODICE_FATTURA = p_cod_fattura,
    COSTO = p_costo
WHERE
    CODICE_INTERVENTO = p_cod_intervento;
END;

/
-- 4. Inserisce una prenotazione
CREATE OR REPLACE
PROCEDURE SP_INSERISCI_PRENOTAZIONE ( 
    p_data_prenotazione DATE,
p_ora_prenotazione VARCHAR2,
p_partecipanti NUMBER, 
    p_pista VARCHAR2,
p_data_gara DATE,
p_ora_gara VARCHAR2,
p_cellulare VARCHAR2, 
    p_pacchetto VARCHAR2,
p_cod_fiscale_admin VARCHAR2
) IS 
    v_check NUMBER;

v_prezzo_pacchetto NUMBER;

v_max_partecipanti NUMBER;
BEGIN 
    SELECT
    COUNT(*)
INTO
    v_check
FROM
    UTENTE
WHERE
    CELLULARE = p_cellulare;

IF v_check = 0 THEN 
        RAISE_APPLICATION_ERROR(-20010, 'Errore: Utente inesistente.');
END IF;

SELECT
    COUNT(*)
INTO
    v_check
FROM
    AMMINISTRATORE
WHERE
    CODICE_FISCALE = p_cod_fiscale_admin;

IF v_check = 0 THEN
        RAISE_APPLICATION_ERROR(-20015, 'Errore: Amministratore non autorizzato o inesistente.');
END IF;

BEGIN 
        SELECT
    PREZZO,
    NUMERO_PARTECIPANTI
INTO
    v_prezzo_pacchetto,
    v_max_partecipanti
FROM
    PACCHETTO_GARA
WHERE
    NOME_PACCHETTO = p_pacchetto
    AND NOME_PISTA = p_pista;

EXCEPTION
WHEN NO_DATA_FOUND THEN 
            RAISE_APPLICATION_ERROR(-20011, 'Errore: Pacchetto non valido per la pista selezionata.');
END;

IF p_partecipanti > v_max_partecipanti THEN 
        RAISE_APPLICATION_ERROR(-20012, 'Errore: I partecipanti superano il limite del pacchetto.');
END IF;

INSERT
    INTO
    PRENOTAZIONE (DATA_PRENOTAZIONE,
    ORA_PRENOTAZIONE,
    QUOTA_ISCRIZIONE,
    NUMERO_PARTECIPANTI_EFFETTIVO,
    NOME_PISTA,
    DATA_GARA,
    ORA_GARA,
    CELLULARE,
    NOME_PACCHETTO,
    CODICE_FISCALE)
VALUES (p_data_prenotazione,
p_ora_prenotazione,
v_prezzo_pacchetto,
p_partecipanti,
p_pista,
p_data_gara,
p_ora_gara,
p_cellulare,
p_pacchetto,
p_cod_fiscale_admin);

EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
        RAISE_APPLICATION_ERROR(-20013, 'Errore: Prenotazione gia esistente per questa data e ora.');
END;

/
-- 5. Registra un Pilota e lo associa al Team
CREATE OR REPLACE
PROCEDURE SP_REGISTRA_PILOTA_TEAM ( 
    p_licenza VARCHAR2,
p_nome VARCHAR2,
p_cognome VARCHAR2,
p_peso NUMBER, 
    p_categoria VARCHAR2,
p_data_nascita DATE,
p_nome_team VARCHAR2,
p_anno_ingaggio NUMBER
) IS 
    v_check NUMBER;
BEGIN 
    SELECT
    COUNT(*)
INTO
    v_check
FROM
    TEAM
WHERE
    NOME_TEAM = p_nome_team;

IF v_check = 0 THEN 
        RAISE_APPLICATION_ERROR(-20020, 'Errore: Il Team specificato non e registrato nel sistema.');
END IF;

SELECT
    COUNT(*)
INTO
    v_check
FROM
    INGAGGIA
WHERE
    NOME_TEAM = p_nome_team
    AND ANNO = p_anno_ingaggio;

IF v_check >= 2 THEN
        RAISE_APPLICATION_ERROR(-20046, 'Errore: Un team non puo ingaggiare piu di 2 piloti l''anno.');
END IF;

SELECT
    COUNT(*)
INTO
    v_check
FROM
    PILOTA
WHERE
    LICENZA = p_licenza;

IF v_check > 0 THEN
        RAISE_APPLICATION_ERROR(-20021, 'Errore: Licenza Pilota gia presente a sistema.');
END IF;

INSERT
    INTO
    PILOTA (LICENZA,
    NOME,
    COGNOME,
    PESO,
    CATEGORIA,
    DATA_NASCITA)
VALUES (p_licenza,
p_nome,
p_cognome,
p_peso,
p_categoria,
p_data_nascita);

INSERT
    INTO
    INGAGGIA (LICENZA,
    NOME_TEAM,
    ANNO)
VALUES (p_licenza,
p_nome_team,
p_anno_ingaggio);
END;

/
-- 6. Registra il pagamento 
CREATE OR REPLACE
PROCEDURE SP_REGISTRA_PAGAMENTO ( 
    p_data_pagamento DATE,
p_ora_pagamento VARCHAR2,
p_modalita VARCHAR2, 
    p_data_prenotazione DATE,
p_ora_prenotazione VARCHAR2,
p_nome_team VARCHAR2
) IS 
    v_cellulare VARCHAR2(100);

v_check NUMBER;
BEGIN
BEGIN
        SELECT
    CELLULARE
INTO
    v_cellulare
FROM
    PRENOTAZIONE
WHERE
    DATA_PRENOTAZIONE = p_data_prenotazione
    AND ORA_PRENOTAZIONE = p_ora_prenotazione;

EXCEPTION
WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20030, 'Errore: La prenotazione specificata non esiste.');
END;

SELECT
    COUNT(*)
INTO
    v_check
FROM
    UTENTE
WHERE
    CELLULARE = v_cellulare;

IF v_check = 0 THEN
        RAISE_APPLICATION_ERROR(-20010, 'Errore: Integrita violata, l''utente della prenotazione non esiste.');
END IF;

SELECT
    COUNT(*)
INTO
    v_check
FROM
    TEAM
WHERE
    NOME_TEAM = p_nome_team;

IF v_check = 0 THEN 
        RAISE_APPLICATION_ERROR(-20031, 'Errore: Il Team specificato per il pagamento non e registrato.');
END IF;

INSERT
    INTO
    PAGAMENTO (DATA_PAGAMENTO,
    ORA_PAGAMENTO,
    MODALITA,
    DATA_PRENOTAZIONE,
    ORA_PRENOTAZIONE,
    NOME_TEAM)
VALUES (p_data_pagamento,
p_ora_pagamento,
p_modalita,
p_data_prenotazione,
p_ora_prenotazione,
p_nome_team);

EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN 
        RAISE_APPLICATION_ERROR(-20032, 'Errore: Pagamento gia registrato per questa data e ora.');
END;

/;

CREATE OR REPLACE
PROCEDURE KARTODROMO.SP_CHIUDI_RIPARAZIONE (
    p_cod_intervento NUMBER,
p_cod_fattura VARCHAR2,
p_costo NUMBER
) IS
    v_num_kart VARCHAR2(100);

v_check NUMBER;
BEGIN
BEGIN
        SELECT
    NUMERO_KART
INTO
    v_num_kart
FROM
    INTERVENTO_RIPARAZIONE
WHERE
    CODICE_INTERVENTO = p_cod_intervento
    AND DATA_FINE IS NULL;

EXCEPTION
WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20096, 'Errore: Impossibile chiudere un intervento inesistente o gia chiuso.');
END;

SELECT
    COUNT(*)
INTO
    v_check
FROM
    FATTURA
WHERE
    CODICE_FATTURA = p_cod_fattura;

IF v_check = 0 THEN
        RAISE_APPLICATION_ERROR(-20063, 'Errore: La Fattura specificata non esiste nel sistema.');
END IF;

SELECT
    COUNT(*)
INTO
    v_check
FROM
    KART
WHERE
    NUMERO_KART = v_num_kart;

IF v_check = 0 THEN
        RAISE_APPLICATION_ERROR(-20061, 'Errore: Integrita violata, il Kart non esiste piu.');
END IF;

UPDATE
    INTERVENTO_RIPARAZIONE
SET
    DATA_FINE = TRUNC(SYSDATE),
    ORA_FINE = TO_CHAR(SYSDATE, 'HH24:MI'),
    CODICE_FATTURA = p_cod_fattura,
    COSTO = p_costo
WHERE
    CODICE_INTERVENTO = p_cod_intervento;
END;

CREATE OR REPLACE
PROCEDURE KARTODROMO.SP_INSERISCI_PRENOTAZIONE ( 
    p_data_prenotazione DATE,
p_ora_prenotazione VARCHAR2,
p_partecipanti NUMBER, 
    p_pista VARCHAR2,
p_data_gara DATE,
p_ora_gara VARCHAR2,
p_cellulare VARCHAR2, 
    p_pacchetto VARCHAR2,
p_cod_fiscale_admin VARCHAR2
) IS 
    v_check NUMBER;

v_prezzo_pacchetto NUMBER;

v_max_partecipanti NUMBER;
BEGIN 
    SELECT
    COUNT(*)
INTO
    v_check
FROM
    UTENTE
WHERE
    CELLULARE = p_cellulare;

IF v_check = 0 THEN 
        RAISE_APPLICATION_ERROR(-20010, 'Errore: Utente inesistente.');
END IF;

SELECT
    COUNT(*)
INTO
    v_check
FROM
    AMMINISTRATORE
WHERE
    CODICE_FISCALE = p_cod_fiscale_admin;

IF v_check = 0 THEN
        RAISE_APPLICATION_ERROR(-20015, 'Errore: Amministratore non autorizzato o inesistente.');
END IF;

BEGIN 
        SELECT
    PREZZO,
    NUMERO_PARTECIPANTI
INTO
    v_prezzo_pacchetto,
    v_max_partecipanti
FROM
    PACCHETTO_GARA
WHERE
    NOME_PACCHETTO = p_pacchetto
    AND NOME_PISTA = p_pista;

EXCEPTION
WHEN NO_DATA_FOUND THEN 
            RAISE_APPLICATION_ERROR(-20011, 'Errore: Pacchetto non valido per la pista selezionata.');
END;

IF p_partecipanti > v_max_partecipanti THEN 
        RAISE_APPLICATION_ERROR(-20012, 'Errore: I partecipanti superano il limite del pacchetto.');
END IF;

INSERT
    INTO
    PRENOTAZIONE (DATA_PRENOTAZIONE,
    ORA_PRENOTAZIONE,
    QUOTA_ISCRIZIONE,
    NUMERO_PARTECIPANTI_EFFETTIVO,
    NOME_PISTA,
    DATA_GARA,
    ORA_GARA,
    CELLULARE,
    NOME_PACCHETTO,
    CODICE_FISCALE)
VALUES (p_data_prenotazione,
p_ora_prenotazione,
v_prezzo_pacchetto,
p_partecipanti,
p_pista,
p_data_gara,
p_ora_gara,
p_cellulare,
p_pacchetto,
p_cod_fiscale_admin);

EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
        RAISE_APPLICATION_ERROR(-20013, 'Errore: Prenotazione gia esistente per questa data e ora.');
END;

CREATE OR REPLACE
PROCEDURE KARTODROMO.SP_REGISTRA_PAGAMENTO ( 
    p_data_pagamento DATE,
p_ora_pagamento VARCHAR2,
p_modalita VARCHAR2, 
    p_data_prenotazione DATE,
p_ora_prenotazione VARCHAR2,
p_nome_team VARCHAR2
) IS 
    v_cellulare VARCHAR2(100);

v_check NUMBER;
BEGIN
BEGIN
        SELECT
    CELLULARE
INTO
    v_cellulare
FROM
    PRENOTAZIONE
WHERE
    DATA_PRENOTAZIONE = p_data_prenotazione
    AND ORA_PRENOTAZIONE = p_ora_prenotazione;

EXCEPTION
WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20030, 'Errore: La prenotazione specificata non esiste.');
END;

SELECT
    COUNT(*)
INTO
    v_check
FROM
    UTENTE
WHERE
    CELLULARE = v_cellulare;

IF v_check = 0 THEN
        RAISE_APPLICATION_ERROR(-20010, 'Errore: Integrita violata, l''utente della prenotazione non esiste.');
END IF;

SELECT
    COUNT(*)
INTO
    v_check
FROM
    TEAM
WHERE
    NOME_TEAM = p_nome_team;

IF v_check = 0 THEN 
        RAISE_APPLICATION_ERROR(-20031, 'Errore: Il Team specificato per il pagamento non e registrato.');
END IF;

INSERT
    INTO
    PAGAMENTO (DATA_PAGAMENTO,
    ORA_PAGAMENTO,
    MODALITA,
    DATA_PRENOTAZIONE,
    ORA_PRENOTAZIONE,
    NOME_TEAM)
VALUES (p_data_pagamento,
p_ora_pagamento,
p_modalita,
p_data_prenotazione,
p_ora_prenotazione,
p_nome_team);

EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN 
        RAISE_APPLICATION_ERROR(-20032, 'Errore: Pagamento gia registrato per questa data e ora.');
END;

CREATE OR REPLACE
PROCEDURE KARTODROMO.SP_REGISTRA_PILOTA_TEAM ( 
    p_licenza VARCHAR2,
p_nome VARCHAR2,
p_cognome VARCHAR2,
p_peso NUMBER, 
    p_categoria VARCHAR2,
p_data_nascita DATE,
p_nome_team VARCHAR2,
p_anno_ingaggio NUMBER
) IS 
    v_check NUMBER;
BEGIN 
    SELECT
    COUNT(*)
INTO
    v_check
FROM
    TEAM
WHERE
    NOME_TEAM = p_nome_team;

IF v_check = 0 THEN 
        RAISE_APPLICATION_ERROR(-20020, 'Errore: Il Team specificato non e registrato nel sistema.');
END IF;

SELECT
    COUNT(*)
INTO
    v_check
FROM
    INGAGGIA
WHERE
    NOME_TEAM = p_nome_team
    AND ANNO = p_anno_ingaggio;

IF v_check >= 2 THEN
        RAISE_APPLICATION_ERROR(-20046, 'Errore: Un team non puo ingaggiare piu di 2 piloti l''anno.');
END IF;

SELECT
    COUNT(*)
INTO
    v_check
FROM
    PILOTA
WHERE
    LICENZA = p_licenza;

IF v_check > 0 THEN
        RAISE_APPLICATION_ERROR(-20021, 'Errore: Licenza Pilota gia presente a sistema.');
END IF;

INSERT
    INTO
    PILOTA (LICENZA,
    NOME,
    COGNOME,
    PESO,
    CATEGORIA,
    DATA_NASCITA)
VALUES (p_licenza,
p_nome,
p_cognome,
p_peso,
p_categoria,
p_data_nascita);

INSERT
    INTO
    INGAGGIA (LICENZA,
    NOME_TEAM,
    ANNO)
VALUES (p_licenza,
p_nome_team,
p_anno_ingaggio);
END;
